# -*- coding: utf-8 -*-
"""test2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qu8Qfkmji0Ldossu6w8EfY4mdz5lFbmy
"""

# @title 1. CÀI ĐẶT THƯ VIỆN & KHỞI TẠO MÔI TRƯỜNG
import os
print("🚀 Đang cài đặt thư viện KHDL & Google AI Studio (Vui lòng đợi)...")
!pip install -q pandas numpy scikit-learn tensorflow matplotlib seaborn faiss-cpu sentence-transformers
!pip install -q google-generativeai

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import google.generativeai as genai
import hashlib

print("✅ Môi trường đã sẵn sàng! Đã kích hoạt kiến trúc Cloud AI.")

# @title 2. LÕI TOÁN HỌC Y KHOA (THIẾT LẬP MỤC TIÊU)
class MedicalMathEngine:
    def __init__(self, weight_kg, height_cm, age, gender, activity_level):
        self.w = weight_kg; self.h = height_cm; self.a = age
        self.g = gender.lower(); self.act = activity_level

    def calculate_bmr(self):
        if self.g == 'nam': return (10 * self.w) + (6.25 * self.h) - (5 * self.a) + 5
        return (10 * self.w) + (6.25 * self.h) - (5 * self.a) - 161

    def calculate_tdee(self):
        mult = {'none': 1.2, 'light': 1.375, 'moderate': 1.55, 'active': 1.725}
        return round(self.calculate_bmr() * mult.get(self.act, 1.2))

    def get_target(self, goal="maintain"):
        tdee = self.calculate_tdee()
        if goal == "lose": return tdee - 500
        elif goal == "gain": return tdee + 500
        return tdee

print("✅ Đã nạp Lõi Toán học Y Khoa.")

# @title 3. DATA LAKE & AI ENGINE (CHUẨN HÓA & MÃ HÓA DỮ LIỆU)
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.utils import class_weight
import pandas as pd
import numpy as np
import hashlib

class GlobalAIEngine:
    def __init__(self):
        print("🌊 BƯỚC 1: Tích hợp Data Lake & Mã hóa Dữ liệu (Hashing)...")
        self.df_usda = pd.read_csv('comprehensive_foods_usda.csv')
        self.df_health = pd.read_csv('foods_health_scores_allergens.csv')
        self.df_allergen = pd.read_csv('foods_allergens.csv')
        self.df_diet = pd.read_csv('foods_dietary_restrictions.csv')
        self.df_healthy = pd.read_csv('healthy_foods_database.csv')

        def generate_standard_hash(text):
            if pd.isna(text): return "UNKNOWN"
            clean_text = str(text).strip().lower()
            hash_str = hashlib.md5(clean_text.encode('utf-8')).hexdigest()[:8].upper()
            return f"FOOD_{hash_str}"

        print(" 🔒 Đang đồng bộ hóa Khóa chính (Primary Key) cho 5 file...")
        self.df_usda['Food_ID'] = self.df_usda['food_name'].apply(generate_standard_hash)
        self.df_healthy['Food_ID'] = self.df_healthy['food_name'].apply(generate_standard_hash)
        self.df_health['Food_ID'] = self.df_health['product_name'].apply(generate_standard_hash)
        self.df_allergen['Food_ID'] = self.df_allergen['product_name'].apply(generate_standard_hash)
        self.df_diet['Food_ID'] = self.df_diet['product_name'].apply(generate_standard_hash)

        temp_db = pd.merge(self.df_health, self.df_allergen[['Food_ID', 'allergens']], on='Food_ID', how='left')
        self.master_db = pd.merge(temp_db, self.df_diet[['Food_ID', 'nova_group']], on='Food_ID', how='left')

        print("✅ Đã hợp nhất thành công 5 nguồn dữ liệu thông qua Mã định danh!")
        self._train_all()

    def _train_all(self):
        print("\n⚙️ BƯỚC 2: Bắt đầu huấn luyện Trí tuệ Nhân tạo...")
        df_ml = self.df_usda.dropna(subset=['calories', 'protein_g', 'fat_g', 'carbs_g']).copy()
        self.lr = LinearRegression().fit(df_ml[['protein_g', 'fat_g', 'carbs_g']], df_ml['calories'])
        self.scl_km = StandardScaler()
        self.kmeans = KMeans(n_clusters=8, random_state=42, n_init=10).fit(self.scl_km.fit_transform(df_ml[['calories', 'protein_g', 'fat_g', 'carbs_g']]))
        df_ml['cluster'] = self.kmeans.labels_
        self.usda_ready = df_ml

        print("\n🧠 Đang huấn luyện [1/2] NutriScore Deep Learning...")
        feat_n = ['energy_kcal', 'proteins_100g', 'fat_100g', 'carbs_100g', 'sugars_100g', 'saturated_fat_100g', 'sodium_100g', 'fiber_100g']
        df_n = self.master_db.dropna(subset=['nutriscore_grade']).copy()
        df_n = df_n[df_n['nutriscore_grade'].isin(['A', 'B', 'C', 'D', 'E'])]
        df_n[feat_n] = df_n[feat_n].fillna(0)

        self.le_n = LabelEncoder()
        y = self.le_n.fit_transform(df_n['nutriscore_grade'])
        self.sc_n = StandardScaler()
        X = self.sc_n.fit_transform(df_n[feat_n])

        cw = dict(enumerate(class_weight.compute_class_weight('balanced', classes=np.unique(y), y=y)))

        # FIX CẤU TRÚC: Tối ưu layer và tăng Dropout lên 0.4 để mô hình bớt học vẹt
        self.model_n = Sequential([
            Input(shape=(8,)),
            Dense(128, activation='relu'), BatchNormalization(), Dropout(0.4),
            Dense(64, activation='relu'), Dropout(0.2),
            Dense(5, activation='softmax')
        ])
        self.model_n.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

        # FIX TỐC ĐỘ: Thêm batch_size=2048, giảm patience=5
        self.model_n.fit(X, y, epochs=100, batch_size=2048, validation_split=0.2, class_weight=cw,
                         callbacks=[EarlyStopping(patience=5, restore_best_weights=True)], verbose=1)

        print("\n🧠 Đang huấn luyện [2/2] Food Category Deep Learning...")
        feat_c = ['calories', 'protein_g', 'fat_g', 'carbs_g', 'sugar_g', 'saturated_fat_g', 'sodium_mg', 'fiber_g']
        df_cat = self.df_usda.dropna(subset=['food_category']).copy()
        df_cat[feat_c] = df_cat[feat_c].fillna(0)
        top_cat = df_cat['food_category'].value_counts().nlargest(8).index
        df_cat = df_cat[df_cat['food_category'].isin(top_cat)]

        self.le_c = LabelEncoder()
        yc = self.le_c.fit_transform(df_cat['food_category'])
        self.sc_c = StandardScaler()
        Xc = self.sc_c.fit_transform(df_cat[feat_c])

        # FIX CẤU TRÚC: Tối ưu layer
        self.model_c = Sequential([
            Input(shape=(8,)),
            Dense(128, activation='relu'), BatchNormalization(), Dropout(0.4),
            Dense(len(self.le_c.classes_), activation='softmax')
        ])
        self.model_c.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

        # FIX TỐC ĐỘ: Thêm batch_size=2048, giảm patience=5
        self.model_c.fit(Xc, yc, epochs=50, batch_size=2048, validation_split=0.2,
                         callbacks=[EarlyStopping(patience=5, restore_best_weights=True)], verbose=1)

        print("\n✅ Core AI Engine & Data Lake đã hoàn toàn sẵn sàng với TỐC ĐỘ TỐI ĐA!")

ai_engine = GlobalAIEngine()

# @title 4. XỬ LÝ NGÔN NGỮ TỰ NHIÊN (RAG + GEMINI 1.5 FLASH)
import faiss
from sentence_transformers import SentenceTransformer
import google.generativeai as genai

# CẤU HÌNH API GEMINI (DÁN API KEY VÀO ĐÂY)
API_KEY = "AIzaSyBVvJEOVhxNxf5BlYxFQSQVI41waI5jwXQ"
genai.configure(api_key=API_KEY)

class ChatCore:
    def __init__(self, engine):
        print("🤖 Đang khởi tạo Hybrid RAG Chatbot với System Instruction...")
        self.engine = engine
        self.embedder = SentenceTransformer('keepitreal/vietnamese-sbert')
        self.data = engine.master_db.head(800)
        docs = [f"Món {r['product_name']} có {r['energy_kcal']} kcal. Nhãn: {r['nutriscore_grade']}" for _, r in self.data.iterrows()]
        embeddings = self.embedder.encode(docs)
        self.index = faiss.IndexFlatL2(embeddings.shape[1])
        self.index.add(np.array(embeddings))

        system_rules = """Bạn là AI chuyên gia dinh dưỡng của MyFitnessPal dành riêng cho thị trường Việt Nam.
BẠN PHẢI TUÂN THỦ NGHIÊM NGẶT CÁC QUY TẮC SAU:
1. BẢO TOÀN DỮ LIỆU SỐ (NUMERICAL DATA): Bạn CHỈ ĐƯỢC PHÉP sử dụng các con số (định lượng, calo, gram) từ phần [DỮ LIỆU HỆ THỐNG TRUY XUẤT]. TUYỆT ĐỐI GIỮ NGUYÊN các con số này, không được tự ý làm tròn, không tính toán sai lệch và cấm bịa đặt số liệu.
2. CHUẨN HÓA THUẬT NGỮ (TERMINOLOGY): BẮT BUỘC giữ nguyên Tiếng Anh cho các danh từ/chỉ số khoa học (Calories, Protein, Fat, Carbs, Fiber, Sodium, NutriScore, BMI, BMR). Cấm dịch thành Đạm, Béo, Tinh bột.
3. NGÔN NGỮ GIAO TIẾP: Trả lời người dùng bằng Tiếng Việt 100%, giọng điệu chuyên nghiệp, y khoa nhưng thân thiện.
4. TÊN RIÊNG (NAMED ENTITIES): Tự động dịch tên thực phẩm (Tiếng Anh) sang Tiếng Việt (VD: "Chicken breast" -> "Ức gà"). Nếu không chắc chắn, hãy giữ nguyên tên Tiếng Anh gốc.
Ví dụ cách trả lời chuẩn: "Dạ, theo cơ sở dữ liệu USDA, 100g Ức gà chứa chính xác 165 Calories và 31g Protein ạ."
"""
        self.llm = genai.GenerativeModel(model_name='gemini-2.5-flash', system_instruction=system_rules)

    def ask(self, query):
        try:
            v = self.embedder.encode([query])
            _, I = self.index.search(np.array(v), k=3)
            context = "\n".join([f"- {self.data.iloc[i]['product_name']} ({self.data.iloc[i]['energy_kcal']} calories, {self.data.iloc[i]['proteins_100g']}g protein)" for i in I[0]])

            prompt = f"[DỮ LIỆU HỆ THỐNG TRUY XUẤT]:\n{context}\n\nCâu hỏi của người dùng: \"{query}\""
            response = self.llm.generate_content(prompt)
            return response.text.replace('**', '')
        except Exception as e: return f"⚠️ Lỗi kết nối AI Studio: {e}"

    def smart_fridge(self, text, max_cal=500):
        kw = {"gà": "chicken", "bò": "beef", "heo": "pork", "lợn": "pork", "cá": "fish", "tôm": "shrimp", "trứng": "egg", "sữa": "milk", "cơm": "rice", "khoai tây": "potato", "cà chua": "tomato", "rau bina": "spinach", "chuối": "banana", "táo": "apple"}
        ext = [en for vn, en in kw.items() if vn in text.lower()]
        if not ext: return "⚠️ Không nhận diện được nguyên liệu phổ biến."
        db = self.engine.master_db.dropna(subset=['ingredients']).copy()
        db['match'] = db['ingredients'].str.lower().apply(lambda x: sum(1 for k in ext if k in x))
        res = db[(db['match'] > 0) & (db['energy_kcal'] <= max_cal)].sort_values(by='match', ascending=False).head(3)
        if res.empty: return "Không tìm thấy món phù hợp."
        return res[['product_name', 'energy_kcal']].to_dict('records')

chat_bot = ChatCore(ai_engine)

# @title 5. LÕI MYFITNESSPAL PREMIUM+ & BUSINESS LOGIC
class MFPPremiumClone:
    def __init__(self, engine, target=2000, allergies=['contains_gluten']):
        self.engine = engine; self.target = target; self.allergies = allergies
        self.logs = pd.DataFrame(columns=['time', 'day', 'meal', 'Food_ID', 'name', 'cal', 'p', 'f', 'net_c', 'score', 'alert'])
        self.fasting = {"status": "OFF", "start": None}; self.daily_goals = {}
        sns.set_theme(style="whitegrid")

    def toggle_fasting(self):
        now = datetime.now().strftime("%H:%M")
        if self.fasting["status"] == "OFF":
            self.fasting = {"status": "ON", "start": now}
            return f"⏳ Bắt đầu Fasting lúc {now}"
        self.fasting["status"] = "OFF"
        return f"🍽️ Kết thúc Fasting lúc {now}"

    def set_daily_goal(self, day, target_cal):
        self.daily_goals[day] = target_cal
        return f"🎯 Mục tiêu {day}: {target_cal} kcal."

    def quick_add(self, meal, cal, p, f, c):
        new = pd.DataFrame([{'time': datetime.now().strftime("%H:%M"), 'day': 'Today', 'meal': meal, 'Food_ID': 'N/A', 'name': '⚡ Quick Add', 'cal': cal, 'p': p, 'f': f, 'net_c': c, 'score': 'N/A', 'alert': 'N/A'}])
        self.logs = pd.concat([self.logs, new], ignore_index=True)
        return f"Đã Quick-Add {cal} kcal vào {meal}."

    def create_custom_food(self, name, cal, p, f, c, fiber=0):
        fid = f"FOOD_{hashlib.md5(name.lower().encode()).hexdigest()[:8].upper()}"
        new_f = pd.DataFrame([{'Food_ID': fid, 'food_name': f"[Custom] {name}", 'calories': cal, 'protein_g': p, 'fat_g': f, 'carbs_g': c, 'fiber_g': fiber, 'cluster': -1}])
        self.engine.usda_ready = pd.concat([self.engine.usda_ready, new_f], ignore_index=True)
        return f"Đã tạo món mới: {name} (ID: {fid})."

    def log_weight(self, weight_kg):
        with open("weight_progress.txt", "a") as f: f.write(f"{datetime.now().strftime('%Y-%m-%d')}: {weight_kg} kg\n")
        return f"⚖️ Lưu cân nặng: {weight_kg} kg."

    def export_data(self):
        if self.logs.empty: return "Trống."
        fn = f"Export_{datetime.now().strftime('%Y%m%d')}.csv"
        self.logs.to_csv(fn, index=False)
        return f"🖨️ Xuất File thành công: {fn}"

    def log(self, meal, food, weight, day='Today'):
        res = self.engine.usda_ready[self.engine.usda_ready['food_name'].str.contains(food, case=False, na=False)]
        if res.empty: return "❌ Không tìm thấy."
        d = res.iloc[0]; r = weight / 100
        nc = max(0, (d['carbs_g']*r) - (d.get('fiber_g', 0)*r))

        try:
            in_d = np.array([[d['calories'], d['protein_g'], d['fat_g'], d['carbs_g'], 0,0,0,0]])
            sc = self.engine.le_n.inverse_transform([np.argmax(self.engine.model_n.predict(self.engine.sc_n.transform(in_d), verbose=0))])[0]
        except: sc = "N/A"

        safe = self.engine.master_db[self.engine.master_db['Food_ID'] == d['Food_ID']]
        msg = "✅ An toàn"
        if not safe.empty:
            for a in self.allergies:
                if safe.iloc[0].get(a) == True: msg = f"⚠️ DỊ ỨNG: {a.upper()}"

        new = pd.DataFrame([{'time': datetime.now().strftime("%H:%M"), 'day': day, 'meal': meal, 'Food_ID': d['Food_ID'], 'name': d['food_name'], 'cal': d['calories']*r, 'p': d['protein_g']*r, 'f': d['fat_g']*r, 'net_c': nc, 'score': sc, 'alert': msg}])
        self.logs = pd.concat([self.logs, new], ignore_index=True)
        return f"[{datetime.now().strftime('%H:%M')}] Logged: {d['food_name']} | AI: {sc} | {msg}"

    def dashboard(self, day='Today'):
        if self.logs.empty: return print("Nhật ký trống.")
        dl = self.logs[self.logs['day'] == day]
        if dl.empty: return print("Không có dữ liệu hôm nay.")
        goal = self.daily_goals.get(day, self.target)
        print("="*60); print(f"📊 MFP PREMIUM DASHBOARD - {day.upper()} | FASTING: {self.fasting['status']}"); print("="*60)
        print(f"▶ NĂNG LƯỢNG: {dl['cal'].sum():.0f} / {goal} kcal")
        worst = dl.loc[dl['cal'].idxmax()]; best = dl.loc[dl['p'].idxmax()]
        print(f"▶ FOOD ANALYSIS: Cao Calo nhất ({worst['name']}) | Giàu Đạm nhất ({best['name']})")

        fig, ax = plt.subplots(1, 2, figsize=(12, 5))
        ax[0].pie([dl['p'].sum(), dl['f'].sum(), dl['net_c'].sum()], labels=['Protein', 'Fat', 'Net Carbs'], autopct='%1.1f%%')
        ax[0].set_title("Macros Distribution")
        sns.barplot(data=dl, x='meal', y='cal', ax=ax[1], palette="viridis")
        ax[1].set_title("Calories by Meal")
        plt.tight_layout(); plt.show()

    def smart_safe_swap(self, food_name, top_k=3):
        item = self.engine.usda_ready[self.engine.usda_ready['food_name'].str.contains(food_name, case=False, na=False)]
        if item.empty: return "❌ Không tìm thấy món ăn gốc."
        t_clus = item.iloc[0]['cluster']; t_cal = item.iloc[0]['calories']

        cands = self.engine.usda_ready[(self.engine.usda_ready['cluster'] == t_clus) &
                                       (self.engine.usda_ready['calories'].between(t_cal*0.9, t_cal*1.1)) &
                                       (~self.engine.usda_ready['food_name'].str.contains(food_name, case=False))]
        safe_cands = []
        blocked = 0
        for _, row in cands.iterrows():
            safe_item = self.engine.master_db[self.engine.master_db['Food_ID'] == row['Food_ID']]
            is_safe = True
            if not safe_item.empty:
                for a in self.allergies:
                    if safe_item.iloc[0].get(a) == True:
                        is_safe = False; blocked += 1; break
            if is_safe: safe_cands.append(row)

        if not safe_cands: return f"⚠️ Đã chặn {blocked} món. Không còn món an toàn."
        res_df = pd.DataFrame(safe_cands).head(top_k)
        res = f"🛡️ Đã chặn {blocked} món nguy hiểm.\n🤖 AI GỢI Ý ĐỔI MÓN:\n"
        for _, r in res_df.iterrows(): res += f"   ✔️ {r['food_name']} ({r['calories']:.0f} kcal)\n"
        return res

    def recommend_healthy_plan(self, day='Today', top_k=3):
        goal = self.daily_goals.get(day, self.target)
        consumed = self.logs[self.logs['day'] == day]['cal'].sum() if not self.logs.empty else 0
        remaining_cal = goal - consumed
        if remaining_cal <= 50: return "⚠️ Bạn đã ăn đủ Calories hôm nay!"

        cands = self.engine.df_healthy[self.engine.df_healthy['calories'] <= remaining_cal].copy()
        if cands.empty: return f"Không tìm thấy món healthy dưới {remaining_cal:.0f} Calories."

        safe_cands = []
        blocked = 0
        for _, row in cands.iterrows():
            safe_item = self.engine.master_db[self.engine.master_db['Food_ID'] == row['Food_ID']]
            is_safe = True
            if not safe_item.empty:
                for a in self.allergies:
                    if safe_item.iloc[0].get(a) == True:
                        is_safe = False; blocked += 1; break
            if is_safe: safe_cands.append(row)

        safe_df = pd.DataFrame(safe_cands)
        if safe_df.empty: return f"⚠️ Đã chặn {blocked} món nguy hiểm. Không còn món an toàn."
        best_meals = safe_df.sort_values(by='health_score', ascending=False).head(top_k)

        res = f"🥗 AI THỰC ĐƠN HEALTHY (Còn lại: < {remaining_cal:.0f} Calories)\n"
        res += f"🛡️ Đã chặn {blocked} món nguy hiểm.\n" + "-"*40 + "\n"
        for _, r in best_meals.iterrows():
            res += f" ✔️ {r['food_name']} | {r['calories']} Calories | Điểm Y Tế: {r['health_score']}/100\n"
        return res

111# @title 6. GIAO DIỆN TƯƠNG TÁC TỔNG HỢP (LIVE DEMO)
def get_num(prompt_text, default=0.0):
    val = input(prompt_text).strip()
    return float(val) if val else default

print("="*60)
print("🩺 KHỞI TẠO HỒ SƠ Y KHOA KHÁCH HÀNG")
w = get_num(" - Cân nặng (kg) [VD: 70]: ", 70)
h = get_num(" - Chiều cao (cm) [VD: 170]: ", 170)
a = get_num(" - Tuổi [VD: 25]: ", 25)
g = input(" - Giới tính (Nam/Nu): ").strip()
medical_profile = MedicalMathEngine(w, h, a, g, 'light')
target_cal = medical_profile.get_target(goal="lose")
print(f"✅ Hệ thống tính toán Calo Mục tiêu (Giảm cân): {target_cal} Calories")

app = MFPPremiumClone(ai_engine, target=target_cal, allergies=['contains_gluten', 'contains_dairy'])

print("\n" + "="*60)
print("👑 HỆ THỐNG AI DINH DƯỠNG - THE ULTIMATE MASTER VERSION")
print("="*60)

while True:
    print("\n📋 MENU KHOA HỌC DỮ LIỆU & MFP PREMIUM:")
    print(" [1] Nhật ký & Quét dị ứng    [2] Quick Add & Custom Food  [3] Cài Đặt Premium (Fasting/Goals)")
    print(" [4] AI Đổi Món An Toàn       [5] NLP Tủ Lạnh              [6] Chatbot Chuyên Gia (Gemini)")
    print(" [7] Dashboard & Analysis     [8] Xuất Dữ liệu (Export)    [9] 🥗 AI Gợi ý Healthy")
    print(" [0] Thoát")
    c = input("👉 Chọn: ").strip()

    try:
        if c == '0': break
        elif c == '1':
            m = input("Bữa (Breakfast/Lunch): "); f = input("Món (Tiếng Anh): "); w = get_num("Gram: ", 100)
            print("🤖:", app.log(m, f, w))
        elif c == '2':
            sub = input(" Chọn (1) Quick Add hoặc (2) Custom Food: ")
            if sub == '1': print("🤖:", app.quick_add(input("Bữa: "), get_num("Calories: "), get_num("Protein: "), get_num("Fat: "), get_num("Carbs: ")))
            elif sub == '2': print("🤖:", app.create_custom_food(input("Tên món: "), get_num("Calories: "), get_num("Protein: "), get_num("Fat: "), get_num("Carbs: ")))
        elif c == '3':
            sub = input(" Chọn (1) Bật/Tắt Fasting, (2) Đặt Goal ngày mai, (3) Lưu cân nặng: ")
            if sub == '1': print("🤖:", app.toggle_fasting())
            elif sub == '2': print("🤖:", app.set_daily_goal("Tomorrow", get_num("Calories: ", 2000)))
            elif sub == '3': print("🤖:", app.log_weight(get_num("Cân nặng mới: ", 70)))
        elif c == '4':
            print(app.smart_safe_swap(input("Nhập món đang chán (Tiếng Anh): ")))
        elif c == '5':
            print("🤖 Tủ Lạnh NLP:\n", chat_bot.smart_fridge(input("Tủ lạnh có gì (Tiếng Việt): ")))
        elif c == '6':
            print("💬 Bắt đầu chat với AI Studio (Nhập 'q' để thoát)")
            while True:
                q = input("👤 Bạn: ")
                if q.lower() == 'q': break
                print("🤖 Gemini:", chat_bot.ask(q))
        elif c == '7': app.dashboard()
        elif c == '8': print("🤖:", app.export_data())
        elif c == '9': print(app.recommend_healthy_plan())
    except Exception as e: print(f"❌ LỖI: {e}")